version: '3.6'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: wiifly
    expose:
      - "${VIRTUAL_PORT:-8001}" 
    environment:
      HTTPS_METHOD: nohttps
#      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST:-bar.com}"
      VIRTUAL_PORT: "${VIRTUAL_PORT:-8001}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-foo.bar.com}"
      VIRTUAL_PATH: "${VIRTUAL_PAHT:-/}"
    volumes:
      - ./config_server.json:/etc/v2ray/config.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    networks:
      - "nginx-proxy"
    restart: always
    
networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"

